name: hello-world-example

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/test-hello-world.yml"

jobs:
  hello-world-example:
    name: "Test: Hello World"
    runs-on: ubuntu-latest
    steps:
      - name: Hello World 101-101
        uses: la-cc/gh-action-hello-world@v0.0.4
        with:
          custom-text: "Hi, my name is 101-101!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
